---
- hosts: all
  remote_user:  ubuntu
  become:       true
  become_user:  root
  become_method: sudo
  tasks:

  - name:  Install htop
    apt:
      name:  htop
      state: present

  - name: add mongodb key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: 68818C72E52529D4

  - name: install mongodb repository
    apt_repository:
      repo: "deb http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse"
      state: "present"
      update_cache: "yes"

  - name: Update APT package manager repositories cache
    shell:
      cmd: sudo apt-get update

  - name: Install mongodb
    apt:
      name: mongodb-org
      state: present
      allow_unauthenticated: yes

  - name: 'Start MongoDB'
    service:
      name: mongod
      state: started
